version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/db:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  web:
    image: elonbot
    build: .
    env_file:
      - .env
    command: gunicorn thebot.wsgi:application --bind 0.0.0.0:8000 --limit-request-line 0 --access-logfile gunicorn.log --workers=4
    ports:
      - "8586:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    restart: "unless-stopped"
    depends_on:
      web:
        condition: service_started
