# Generated by Django 4.0.2 on 2022-02-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerange_lower', models.IntegerField()),
                ('timerange_upper', models.IntegerField()),
                ('url', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
