# Generated by Django 4.0.2 on 2022-02-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
