# Generated by Django 4.0.2 on 2022-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0002_keyword_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='ticker',
            field=models.CharField(default='BTC', max_length=50),
            preserve_default=False,
        ),
    ]
