# Generated by Django 4.0.2 on 2022-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0003_keyword_ticker'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='webhook',
            constraint=models.UniqueConstraint(fields=('timerange_lower', 'timerange_upper'), name='user_universe_constraint'),
        ),
    ]
