# Generated by Django 4.1.7 on 2023-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0006_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=30)),
                ('author_id', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
